# Description: This GitHub Actions workflow is used to deploy a Vercel Preview Deployment for a pull request on the main branch.
name: GitHub Actions Vercel Preview Deployment
on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--preview"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
